config_version: "2023.08.12"
schema_list:
  - schema: quick5
  - schema: quick5de
  - schema: quick5dewin
switcher:
  caption: 〔Settings〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
    - F2
  save_options:
    - full_shape
    - ascii_punct
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
  fold_options: false
  abbreviate_options: false
  option_list_separator: "／"
menu:
  page_size: 9
punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape
key_binder:
  bindings:
    __patch:
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
