# Rime dictionary
# encoding: utf-8
#
# f_mysecretphrases.dict.yaml
#

---
name: my
version: "2022.07.19"
sort: by_weight
use_preset_vocabulary: true
...
example@gmail.com	zmail	10000000000
example@gmail.com	zmail	9999999999
example@yahoo.com	zmail	9999999998
example	zname	9999999997
example	zname	9999999996







