# Rime dictionary
# encoding: utf-8
#
# f_mysecretphrases.dict.yaml
#

---
name: myde
version: "2022.07.19"
sort: by_weight
use_preset_vocabulary: true
...
example@gmail.com	ymail	10000000000
example@gmail.com	ymail	9999999999
example@yahoo.com	ymail	9999999998
example	yname	9999999997
example	yname	9999999996







