---
name: quick5.extended
version: "2026.01.15"
sort: by_weight
max_phrase_length: 3
use_preset_vocabulary: true
import_tables:
  - anime
  - cantonese
  - chat
  - game
  - hakka
  - hangyl
  - history
  - lun
  - mix
  - moe
  - movie
  - music
  - myde
  - net
  - physics
  - place
  - poetry
  - quick5
  - quicksymbols
  - sgmain
  - sgplus
  - sgplus2
  - user
  - vietnamese
  - vocab
