---
name: quicksymbolsde
version: "2023.03.07"
sort: by_weight
use_preset_vocabulary: false
...
α	yalpha
β	ybeta
γ	ygamma
δ	ydelta
ε	yepsilon
ζ	yzeta
η	yeta
θ	ytheta
ι	yiota
ι	yjota
κ	ykappa
λ	ylambda
μ	ymu
μ	ymy
ν	ynu
ν	yny
ξ	yxi
ο	yomicron
ο	yomikron
π	ypi
ρ	yrho
σ	ysigma
τ	ytau
υ	yupsilon
υ	yypsilon
φ	yphi
χ	ychi
ψ	ypsi
ω	yomega
Α	yalpha
Β	ybeta
Γ	ygamma
Δ	ydelta
Ε	yepsilon
Ζ	yzeta
Η	yeta
Θ	ytheta
Ι	yiota
Ι	yjota
Κ	ykappa
Λ	ylambda
Μ	ymu
Μ	ymy
Ν	ynu
Ν	yny
Ξ	yxi
Ο	yomicron
Ο	yomikron
Π	ypi
Ρ	yrho
Σ	ysigma
Τ	ytau
Υ	yupsilon
Υ	yypsilon
Φ	yphi
Χ	ychi
Ψ	ypsi
Ω	yomega
Ω	yohm
ϵ	yepsilon
ϑ	ytheta
ϰ	ykappa
ϖ	ypi
ϱ	yrho
ς	ysigma
ϕ	yphi
Ϝ	ydigamma
ϝ	ydigamma
∂	ypartial
∇	ynabla
∞	yinfty
ℵ	yaleph
√	ysqrt
√	ysurd
√	ywurzel
±	ypm
×	ytimes
×	ymal
÷	ydiv
÷	ydurch
∘	ycirc
⊕	yoplus
⊗	yotimes
∅	yempty
∈	yin
∉	ynotin
∋	yni
∩	ycap
∪	ycup
⊂	ysubset
⊃	ysupset
⊆	ysubseteq
⊇	ysupseteq
≠	yne
≡	yequiv
≅	ycong
≈	yapprox
≤	yle
≤	ysmaller
≥	yge
≥	ybigger
∀	yforall
∃	yexists
∨	yor
∧	yand
∨	yvee
∧	ywedge
¬	yneg
→	yto
∑	ysum
∏	yprod
∐	ycoprod
∫	yint
∮	yoint
ぁ	yxa
あ	ya
ぃ	yxi
い	yi
ぅ	yxu
う	yu
ぇ	yxe
え	ye
ぉ	yxo
お	yo
か	yka
が	yga
き	yki
ぎ	ygi
く	yku
ぐ	ygu
け	yke
げ	yge
こ	yko
ご	ygo
さ	ysa
ざ	yza
し	ysi
じ	yzi
す	ysu
ず	yzu
せ	yse
ぜ	yze
そ	yso
ぞ	yzo
た	yta
だ	yda
ち	yti
ぢ	ydi
っ	yxtu
つ	ytu
づ	ydu
て	yte
で	yde
と	yto
ど	ydo
な	yna
に	yni
ぬ	ynu
ね	yne
の	yno
は	yha
ば	yba
ぱ	ypa
ひ	yhi
び	ybi
ぴ	ypi
ふ	yhu
ぶ	ybu
ぷ	ypu
へ	yhe
べ	ybe
ぺ	ype
ほ	yho
ぼ	ybo
ぽ	ypo
ま	yma
み	ymi
む	ymu
め	yme
も	ymo
ゃ	yxya
や	yya
ゅ	yxyu
ゆ	yyu
ょ	yxyo
よ	yyo
ら	yra
り	yri
る	yru
れ	yre
ろ	yro
ゎ	yxwa
わ	ywa
ゐ	ywi
ゑ	ywe
を	ywo
ん	yn
ゔ	yvu
ァ	yxa
ア	ya
ィ	yxi
イ	yi
ゥ	yxu
ウ	yu
ェ	yxe
エ	ye
ォ	yxo
オ	yo
カ	yka
ガ	yga
キ	yki
ギ	ygi
ク	yku
グ	ygu
ケ	yke
ゲ	yge
コ	yko
ゴ	ygo
サ	ysa
ザ	yza
シ	ysi
ジ	yzi
ス	ysu
ズ	yzu
セ	yse
ゼ	yze
ソ	yso
ゾ	yzo
タ	yta
ダ	yda
チ	yti
ヂ	ydi
ッ	yxtu
ツ	ytu
ヅ	ydu
テ	yte
デ	yde
ト	yto
ド	ydo
ナ	yna
ニ	yni
ヌ	ynu
ネ	yne
ノ	yno
ハ	yha
バ	yba
パ	ypa
ヒ	yhi
ビ	ybi
ピ	ypi
フ	yhu
ブ	ybu
プ	ypu
ヘ	yhe
ベ	ybe
ペ	ype
ホ	yho
ボ	ybo
ポ	ypo
マ	yma
ミ	ymi
ム	ymu
メ	yme
モ	ymo
ャ	yxya
ヤ	yya
ュ	yxyu
ユ	yyu
ョ	yxyo
ヨ	yyo
ラ	yra
リ	yri
ル	yru
レ	yre
ロ	yro
ヮ	yxwa
ワ	ywa
ヰ	ywi
ヱ	ywe
ヲ	ywo
ン	yn
ヴ	yvu
ヵ	yxka
ヶ	yxke
ㄅ	ybo
ㄆ	ypo
ㄇ	ymo
ㄈ	yfo
ㄉ	yde
ㄊ	yte
ㄋ	yne
ㄌ	yle
ㄍ	yge
ㄎ	yke
ㄏ	yhe
ㄐ	yji
ㄑ	yqi
ㄒ	yxi
ㄓ	yzhi
ㄔ	ychi
ㄕ	yshi
ㄖ	yri
ㄗ	yzi
ㄘ	yci
ㄙ	ysi
ㄧ	yi
ㄨ	yu
ㄩ	yyu
ㄚ	ya
ㄛ	yo
ㄜ	yee
ㄝ	ye
ㄞ	yai
ㄟ	yei
ㄠ	yao
ㄡ	you
ㄢ	yan
ㄣ	yen
ㄤ	yang
ㄥ	yeng
ㄦ	yer
ˊ	ym
ˇ	yn
ˋ	yo
