---
name: quick5de.extended
version: "2023.03.07"
sort: by_weight
encoder:
  exclude_patterns:
    - "^y.*$"
max_phrase_length: 3
use_preset_vocabulary: true
import_tables:
  - anime
  - cantonese
  - chat
  - game
  - hakka
  - hangylde
  - history
  - lun
  - mix
  - moe
  - movie
  - music
  - myde
  - net
  - physics
  - place
  - poetry
  - quick5de
  - quicksymbolsde
  - sgmain
  - sgplus
  - sgplus2
  - user
  - vietnamese
  - vocab
