patch:
  show_notifications_when: appropriate
  style/color_scheme: macos_dark
  preset_color_schemes:
    macos_dark:
      author: "YS-Wong@GitHub"
      font_face: "Helvetica"
      font_point: 16.0
      label_font_face: "Helvetica"
      label_font_point: 13.0
      comment_font_face: "Helvetica"
      comment_font_point: 13.0
      candidate_list_layout: linear
      text_orientation: horizontal
      inline_preedit: true
      corner_radius: 6.0
      hilited_corner_radius: 4.0
      border_height: 2.0
      border_width: 2.0
      color_space: srgb
      back_color: 0x1E1E1E
      border_color: 0x1E1E1E
      candidate_text_color: 0xE9E9E9
      comment_text_color: 0x999999
      label_color: 0x999999
      hilited_candidate_back_color: 0xD1592B
      hilited_candidate_text_color: 0xFFFFFF
      hilited_comment_text_color: 0x999999
      hilited_candidate_label_color: 0xFFFFFF
      text_color: 0x424242
      hilited_text_color: 0x999999
app_options:
  com.apple.Spotlight:
    ascii_mode: false
