patch:
    keyboard_layout: USExtended
    show_notifications_when: appropriate
    style:
        border_height: 2.0
        border_width: 2.0
        candidate_list_layout: linear
        color_scheme: aqua
        color_scheme_dark: macos_dark
        comment_font_face: "SF Pro"
        comment_font_point: 13.0
        corner_radius: 6.0
        font_face: "SF Pro"
        font_point: 16.0
        hilited_corner_radius: 4.0
        inline_preedit: true
        label_font_face: "SF Pro"
        label_font_point: 13.0
        text_orientation: horizontal
    preset_color_schemes:
        aqua:
            author: 佛振 <chen.sst@gmail.com>
            back_color: "0xEEECEEEE"
            candidate_text_color: "0x000000"
            color_space: srgb
            comment_text_color: "0x5A5A5A"
            hilited_candidate_back_color: "0xEEFA3A0A"
            hilited_candidate_text_color: "0xFFFFFF"
            hilited_comment_text_color: "0xFCAC9D"
            hilited_text_color: "0x000000"
            name: 碧水／Aqua
            text_color: "0x606060"
        macos_dark:
            author: "easonwong-de@GitHub"
            back_color: 0x1E1E1E
            border_color: 0x1E1E1E
            candidate_text_color: 0xE9E9E9
            color_space: srgb
            comment_text_color: 0x999999
            hilited_candidate_back_color: 0xD1592B
            hilited_candidate_label_color: 0xFFFFFF
            hilited_candidate_text_color: 0xFFFFFF
            hilited_comment_text_color: 0x999999
            hilited_text_color: 0x999999
            label_color: 0x999999
            text_color: 0x424242
app_options:
    com.apple.Spotlight:
        ascii_mode: false
