config_version: "2023.08.12"
patch:
    punctuator/import_preset: symbolsdewin
    recognizer/patterns/punct: "^/([0-9]0?|[A-Za-z]+)$"
punctuator:
    full_shape:
        " ": { commit: "　" }
        ",": { commit: ， }
        ".": [。, ⋯⋯]
        "`": ["^", ＾]
        "~": ["°", "℃", ℉]
        "&": [、, "/", ／, ÷, "{", ｛, 〖]
        "-": ['\', ＼]
        "_": { commit: ？ }
        "<": { commit: ； }
        ">": { commit: ： }
        "|": { pair: ["『", "』"] }
        "@": { pair: ["「", "」"] }
        "#": ["§", ·, ・]
        "+": ["`", ‵, ‶, ‷]
        "=": [′, ″, ‴, ⁗]
        "!": { commit: ！ }
        "\\": ["#", ＃, №, ⌘, "#INSTRUMENTAL", 《, 〈, «, ‹, "<", "|", ｜, 》, 〉, », ›, ">", "¦", "‖"]
        "%": ["%", ％, ‰, ‱]
        "$": ["€", "$", "£", "¥", "¢", "¤", ₩]
        "^": ["&", ＆]
        "}": ["*", ＊, ·, ・, ×, ※]
        "*": ["(", （, "[", ［, 〔, 【, 〖]
        "(": [")", ）, "]", ］, 〕, 】, 〗]
        "/": ["-", －, −]
        "?": ——
        "]": ["+", ～, "~", ≈, ≋, ≃, ≅, ≇, ∽, ⋍, ≌]
        ")": ["=", ＝, ≠, "}", ｝]
    half_shape:
        ",": { commit: ， }
        ".": [。, ⋯⋯]
        "`": ["^", ＾]
        "~": ["°", "℃", ℉]
        "&": [、, "/", ／, ÷, "{", ｛, 〖]
        "-": ['\', ＼]
        "_": { commit: ？ }
        "<": { commit: ； }
        ">": { commit: ： }
        "|": { pair: ["『", "』"] }
        "@": { pair: ["「", "」"] }
        "#": ["§", ·, ・]
        "+": ["`", ‵, ‶, ‷]
        "=": [′, ″, ‴, ⁗]
        "!": { commit: ！ }
        "\\": ["#", ＃, №, ⌘, "#INSTRUMENTAL", 《, 〈, «, ‹, "<", "|", ｜, 》, 〉, », ›, ">", "¦", "‖"]
        "%": ["%", ％, ‰, ‱]
        "$": ["€", "$", "£", "¥", "¢", "¤", ₩]
        "^": ["&", ＆]
        "}": ["*", ＊, ·, ・, ×, ※]
        "*": ["(", （, "[", ［, 〔, 【, 〖]
        "(": [")", ）, "]", ］, 〕, 】, 〗]
        "/": ["-", －, −]
        "?": ——
        "]": ["+", ～, "~", ≈, ≋, ≃, ≅, ≇, ∽, ⋍, ≌]
        ")": ["=", ＝, ≠, "}", ｝]
