---
name: vietnamese
version: "2023.03.07"
sort: by_weight
use_preset_vocabulary: true
max_phrase_length: 1
...
𧵑終
𧵑公
一𪜀
噲𪜀
如𪜀
吶𪜀
咍𪜀
或𪜀
慄𪜀
歐𪜀
𠬠吝
𠬠𠄧
𠬠𣅶
𠬠𠃣
𠬠堆
𡥵𠬠
𠬠唏
𠬠𤾓
𠬠𠦳
𠬠丐
𠬠兆
𠬠萬
𠬠徊
固體
固𨤔
固欺
固條
兜固
固歲
固𫯳
固權
固理
𠃣固
仍𦓡
𠊛些
𡥵𠊛
𢧚𠊛
𠊛𠸗
𠊛越
命𠊛
𤞦𠊛
𥪝欺
特別
特色
特點
特產
特區
特權
特使
特務
空體
𠮩空
空氣
如空
航空
空牢
空𠸥
空想
曠空
空之
壓力空氣
防空
空包𣇞
𠬃空
𡎥空
㐌𥹰
㐌曾
𠇍欺
𠇍埃
唄埃
唄吏
朱別
爫朱
底朱
朱𢧚
朱雀
各位
各伴
眾碎
茹碎
碎伵
於吏
茹於
於終
於妬
於兜
彈翁
翁婆
翁𦓅
翁老
翁偈
魚翁
𧿨𧗱
𧗱茹
𠫾𧗱
底吏
底朱
調拱
節元旦
𦤾坭
𡢐呢
丐呢
𣅶呢
𡨸喃
𫥨𠓨
𠓨曠
𠫾𠓨
𠃣𡗉
𡗉欺
𡗉𠳒
分𡗉
偀㛪
偀姉
偀姉㛪
偀戶
偀払
𡢐妬
芇妬
丐妬
於妬
徊妬
自妬
如勢
如丕
如𪜀
如空
如勢芇
如𫇰
自由
自然
自動
自𨉟
自治
自妬
自𥹰
𥪝欺
𠓀欺
堆欺
固欺
欺芇
𣦍欺
𠃣欺
欺迺
𡗉欺
𡢐欺
常欺
𠇍欺
豫𨕭
𠸥𨕭
仕𫥨
認𫥨
𫥨𠫾
𫥨𠓨
𠫾𫥨
𢣂𫥨
𠃣𫥨
𫥨𨤔
造𫥨
盤𫥨
𠸥𫥨
𫥨陣
𢖵𫥨
耒𫥨
丕𦓡
仍𦓡
𦓡推
邊沛
𧿨吏
群吏
底吏
於吏
𢖵吏
𤯩吏
𢣂吏
捲吏
唄吏
𠫾ㇴ吏ㇴ
回吏
群吏
時間
時代
時節
暫時
時𣇞
時期
時機
急時
丕㖘
𢆥𠸗
𢆥箕
祝𢜠𢆥㵋
𨖅𢆥
役爫
爫朱
爫之
𠫾爫
爫衝
排爫
𠫾爫役
格爫
爫牢
爫客
爫紙
爫役
𣇞爫役
爫務
茹文
茹渃
茹行
茹祠
茹碎
茹於
茹𨷶
茹欱
茹𤤰
茹囚
茹傷
茹重
茹𫯳
茹廚
𧗱茹
茹𥘷
𢖵茹
茹客
茹鏰
茹儒
茹博學
息𨉟
自𨉟
𠅳𨉟
下𨉟
𠫾爫
𫥨𠫾
𠫾戈
𠫾步
𠫾𨔈
𠬃𠫾
塘𠫾
𠫾𫥨
𠫾塊
襖𠫾𩅹
𠫾𠓨
𠫾爫役
𠫾遶
𠫾蹎
𠫾𧗱
𠫾ㇴ吏ㇴ
𠫾𦣰
𡥵𠊛
𡥵𡛔
𡥵𤳇
婆𡥵
𥘷𡥵
𡥵𡮣
𡥵𠬠
𡮣𡥵
在牢
現在
在𡊲
在為
內在
𠄩𩈘
次𠄩
被動
防備
設備
役爫
役務
工役
𠫾爫役
分役
爫役
𣇞爫役
軍事
民事
世事
事物
領事
總領事
起事
事實
𧼋遶
𠫾遶
丐妬
丐呢
𠬠丐
丐之
曾丐
為勢
台為
為牢
在為
𤳄為
吶𡀯
吶𪜀
吶終
㗂吶
吶𨔈
姑教
姑娘
𣈜𣎃
𣈜𫢩
𣈜𠸗
𣈜𡢐
𣈜禮
常𣈜
班𣈜
𣈜箕
𣈜常
最𣈜
𣈜務
㵋低
𢷮㵋
祝𢜠𢆥㵋
𨅸𨖲
𨖲𤖹
捲𨖲
慄𪜀
偀戶
𠸜戶
戶口
彈婆
翁婆
婆𡥵
老婆
婆外
婆內
局𠁀
入局
局生
史冊
冊引
卷冊
讀冊
同義
同音
共同
同意
銅鉑
垌平
𩵜垌
𡢐妬
𡢐呢
𣋚𡢐
𣈜𡢐
𡢐低
𡢐共
𡢐欺
𡢐歇
𡢐𠯆
𡢐𠸗
𠓀𡢐
當今
咍𪜀
咍牢
咍過
𠁀𤯩
𤯩吏
𤯩𣩂
扒𤯩
咹𤯩
常年
年少
十年
元年
青年
成年
𧿨𢧚
朱𢧚
𢧚𠊛
朱別
特別
別包
分別
曉別
恪別
別兜
暫別
別𩈘
別條
認別
感𧡊
𥆾𧡊
𣗓曾𧡊
耒𫥨
城庯
城市
佔城
成功
長成
成分
成此
形成
成年
誠實
恪別
恪常
次𠄼
坦渃
渃外
茹渃
渃眜
滝渃
渃花
渃㕵
渃𤊡
渃越
渃炊
𡽫渃
渃𥒥
渃𣖙
渃茶
𢭲細
戈𠁀
𠫾戈
𣋚戈
𠬃戈
畢哿
𦓅哿
歇哿
共產
共和
總共
𡢐共
共同
爫之
莊之
空之
丐之
𠓀低
㵋低
𣇞低
𡢐低
兜低
數量
𨷶數
𣘃數
民數
指數
數𠃣
數料
卒數
都數
數黰
𠁦數
縁數
係數
營數
指數經濟
歲𥘷
𥘷歲
固歲
𡮈歲
菭歲
𠃣歲
𢜠歲
次長
次一
次二
次𠄩
次𠀧
次四
次𠄼
次𦒹
次𬙞
次要
時期
花旗
下旗
南圻
北圻
中圻
偀㛪
姉㛪
㛪𡮣
㛪重
㛪𫯳
偀姉㛪
𥘷㛪
一𪜀
唯一
𠃣一
一定
統一
萬一
第一
次一
𠓀欺
𠓀低
𠓀𩈘
𪰂𠓀
𠓀𡢐
徊𠓀
各伴
伴𫇰
伴鐄
意想
意見
意義
意志
注意
適意
㗂意
𡨹意
𢢲意
同意
意𢣂
影響
形影
影焒
紙影
憑證
平常
太平
平安
和平
太平洋
垌平
金朋
勢芇
芇妬
欺芇
分芇
如勢芇
徊芇
頭先
扒頭
班頭
𨅸頭
𨷑頭
𨀈頭
頭𣎃
吝頭
拖頭
吝頭先
投機
朝阮
𠶢哴
格爫
革命
改革
𡦂曰
𣘃曰
紙曰書
尋曉
𠬠𣅶
𣅶呢
理想
理由
固理
物理
物理學
心理
地理
助理
正式
正體
政府
政治
財政
政治家
政治犯
政黨
地政治
執政
𣈜𣎃
菭𣎃
頭𣎃
𣎃四
社會
機會
國會
入會
社會主義
﨤憢
打憢
調憢
𣗓曾
𣗓曾𧡊
𠬠吝
吝頭
吝頭先
自由
由探
縁由
理由
莊𣃣
文化
茹文
文學
文明
文𨤔
文萊
漢文
回文
工作
工人
工藝
工業
工役
大工業
分工
卷冊
捲𨖲
捲吏
調查
調憢
調拱
條件
固條
都條
別條
渃花
葻花
𥒥花
花茶
花旗
中華
分𡘯
𡚢𡘯
仉𡘯
莊埃
埃乃
唄埃
埃及
埃ㇴ
𠇍埃
次𠀧
堆𠀧
爸媽
㗂吶
卒㗂
㗂越
㗂英
㗂法
㗂日
㗂中國
㗂德
㗂意
㗂美
㗂中
芒㗂
塘庯
塘𠫾
引塘
𨷑塘
塘鐵
塘高速
糖𥽢
天堂
學堂
女學堂
佛堂
教堂
後堂
內堂
世界
世紀
世事
世俗
新世界
替品
如勢
勢芇
為勢
氣勢
形勢
地勢
如勢芇
𣗓曾
𣗓曾𧡊
㐌曾
曾丐
現𫢩
𣋚𫢩
𣈜𫢩
𦤾坭
泣坭
𦣰坭
傳形
形式
情形
形𦘧
形勢
形影
隊形
形成
現前
𩈘前
前定
前提
前途
前人
前史
錢鉑
錢𩈘
錢紙
眾些
𠊛些
𪝳些
指南
越南
海南
洲南極
南大洋
南洋
南非
𪰂南
南美
南圻
沔南
𧆄南
越南
𠊛越
渃越
㗂越
漢越
中心
中國
節中秋
㗂中國
中非
地中海
中學
中心研究
㗂中
中華
沔中
中圻
禮中秋
𠮩空
歲𥘷
𥘷𡥵
𥘷歲
茹𥘷
𥘷㛪
嫩𥘷
𠸜噲
噠𠸜
𠸜戶
𠸜俗
𨖅𠸜
𥏌焒
實現
誠實
𣦍實
事實
吒媄
𢂞媄
莊勤
慇勤
勤要
句𡀯
吶𡀯
𡀯情
𢲧𡀯
芒㗂
姉㛪
偀姉
偀姉㛪
𣈜禮
旬禮
𨢇禮
禮儀
禮中秋
禮教
𥆾𧡊
𥆾終
國家
國際
國會
祖國
外國
國防
國語
中國
㗂中國
帝國德
王國西班牙
王國丹麥
國營
英國
王國英
高級
最高
高原
提高
朝高
高賖
高點
高上
高𢢲
高棉
塘高速
𠫾步
步隊
步行
𧼋步
部長
淎北部
部首
部下
下部
𤞦𠊛
排書
包書
書電子
斤書
紙曰書
盒書
最後書
祝書
戰爭
鬥爭
競爭
爭論
彈爭
幅幀
傳幀
盤𢬣
𢺺𢬣
包𢬣
蹎𢬣
𢬣𤽸
𢭲𢬣
𢝙𢚸
通信
資訊
德信
吀纇
吀嘲
求吀
人民
民主
民數
民廊
魚民
殖民
民事
民黰
民舉
民權
民衛
聯省
過程
咍過
過𡗋
咹㕵
咹粓
咹𤯩
盤咹
咹試
式咹
房咹
貪咹
店咹
油咹
咹𢜠
情𢞅
要求
主要
勤要
𦓅要
𡮈要
必要
次要
重要
要點
要人
𡞕重
讀者
讀冊
㹥𣩂
𣩂𨅸
𣩂吒
𤯩𣩂
場合
市場
媒場
飛場
場學
場𠖤
場大學
場小學
價市場
媒場學
魚場
部長
長成
次長
船長
黨長
隊長
科長
𡖡長
生長
師長
首長
長科
茹行
銀行
𨷶行
行客
學行
執行
行星
行廊
舉行
步行
銀行𧖱
交行
德行
行𡦂
航空
噠航
航海
𦖑𠳒
𦖑唏
色𢢲
𢢲𤳇
𢢲老
𢢲縁
𢢲意
𢢲𢚸
高𢢲
字典
紅十字
𠢞拖
𡮈歲
𡮈要
𠊟𡮈
仉𡮈
姅𣎀
姅務
莊𠯆
𡢐𠯆
平常
常年
常𣈜
不常
恪常
𫀅常
易常
𣈜常
五常
失常
常欺
常日
常常
文學
大學
科學
學生
排學
學習
場學
學者
學行
小學
哲學
史學
學院
化學
𠰺學
生學
場大學
學問
物理學
動物學
入學
神學
考古學
古生物學
中學
場小學
藥學
人類學
分類學
科學技術
地質學
學屬𢚸
學堂
女學堂
媒場學
林學
儒學
博學
茹博學
亞東
䬔東
東洋
𣷷東
東藥
𪰂東
𠅍𠰺
𠅍務
載𨑜
坦渃
動坦
𤀘坦
坦客
𣛤坦
坦墆
𧸝𠹾
半音
半島
半輔音
併算
反對
人類
人類學
分類
分類學
品類
或𪜀
𠓀𩈘
𩈘陣
錢𩈘
﨤𩈘
𩈘𦝄
𠄩𩈘
都𩈘
𨷑𩈘
別𩈘
認𩈘
𩈘前
夾𩈘
𩈘𡗶
徐䀡
情𢞅
情感
情形
𡀯情
𢞂情
恩情
焒情
景情
情恩
渃外
邊外
海外
外國
婆外
外交
外𠰘
邊外
家庭邊內
邊沛
邊賴
堆邊
在牢
為牢
空牢
𠶢牢
咍牢
𠹲牢
莊牢
爫牢
𣋀閻王
𣋀海王
𣋀天王
𣋀土
𣋀木
𣋀火
𣋀金
𣋀水
𣋀天狼
𣋀北極
𣋀北斗
𤀘坦
如丕
丕𦓡
丕㖘
𨖅張
妝點
𠭤𠳒
認𠳒
𦖑𠳒
𠳐𠳒
拖𠳒
𡗉𠳒
𡨹𠳒
𠃣𠳒
歇唏
𡢐歇
歇哿
歇務
認𫥨
公認
認𠳒
認別
認𩈘
兜固
別兜
於兜
兜低
音聲
傳聲
回聲
青年
青天
青龍
清查
清算
清心
古典
今古
音樂古典
蒙古
考古學
古生物學
古都
𤳄為
𢚸卒
𢞂𢚸
焒𢚸
𧁷𢚸
𢢲𢚸
𢝙𢚸
屬𢚸
學屬𢚸
𡨹𢚸
幅幀
𠬠兆
𣦍欺
𣦍𥐉
𣦍實
𧵆賖
使用
日用
通用
關重
𡞕重
茹重
㛪重
重要
固𫯳
㛪𫯳
茹𫯳
分𤾓
分𡘯
分別
成分
分芇
多分
分𤖹
分𢺺
分佈
分類
分類學
分工
合分
口分
分𡗉
分子
分役
女𖿱
婦女
女神
玉女
女學堂
𧿨吏
𧿨𧗱
𧿨𢧚
𠓨曠
曠空
𠸥𨕭
空𠸥
𠸥𫥨
關重
機關
聯關
關係
海關
關心
觀點
參觀
觀音
無義
人員
生員
教員
湖水
論拠
拠點
民廊
行廊
春秋
務春
回春
𢣂𫥨
𢣂吏
意𢣂
感𢣂
𧁷𢣂
𢣂䏾
通報
排報
預報
紙報
基本
本地
𣷷日本
日本
大本營
本營
出版
版圖
適合
適意
解釋
註釋
易傷
感傷
𢖵傷
總共
總結
總領事
總統
總面積
𣘃數
撐蘿𣘃
𣘃曰
楛𣘃
核仁
傳形
傳幀
傳聲
局𠁀
𠁀𤯩
戈𠁀
𥹰𠁀
𢖵𠁀
𦓅𠁀
犯法
法治
㗂法
法權
法屬
中心
心神
清心
心理
中心研究
關心
𧵆賖
高賖
﨤憢
扒﨤
﨤𩈘
渃眜
𤎜眜
𡦂眜
價眜
𤯆眜
北冰洋
𣋀北極
𣋀北斗
北斗七星
淎北部
北京
𪰂北
北美
北圻
沔北
𧆄北
聰明
文明
英明
精明
元年
元音
節元旦
紀元
二元
源𤎜
詞源
高原
西原
太原
次四
𣎃四
四海
油咹
默𠶢
𠶢牢
𠶢哴
默𠶢
價値
打價
鬥價
價眜
價市場
下價
噠價
𡎥空
大學
大使
場大學
大工業
洲大洋
大西洋
南大洋
加拿大
大陸
大本營
大營
大儒
現代
時代
朝代
近代
包𣇞
𣊾𣇞
𣇞低
時𣇞
莊包𣇞
空包𣇞
𣇞爫役
𣇞𥹰
獨身
身體
形𦘧
牟𦘧
輪輪
輪𠰘
公司
𡥵𡛔
伯𡛔
製造
人造
造𫥨
造化
建造
𣋚𫢩
𣋚𡢐
𣋚戈
𣋚箕
𣋚𠸗
𣋚箕
務春
䬔務
爫務
歇務
務秋
𠅍務
姅務
𣈜務
莊埃
莊勤
莊包𣇞
莊之
莊𠯆
莊他
莊𣃣
莊牢
𦓡推
喂推
牟色
牟綠
牟黰
牟𦘧
𢲧戰
𢲧𡀯
𢲧𥩯
解釋
解決
引解
解義
句𡀯
句𠳨
人德
㗂德
德行
德信
嗣德
帝國德
觀點
地點
特點
妝點
指點
高點
拠點
要點
𡨹意
𡨹𠳒
𡨹𢚸
𡨹𠰘
𡨹𡊲
卒業
卒䏾
𢚸卒
卒數
卒㗂
役務
義務
內務
教務
特務
𠁦數
𢘾𡗶
撐䏧𡗶
𡗶𩅹
呌𡗶
𩈘𡗶
𢖵吏
想𢖵
𢖵𠁀
𢖵茹
𢖵𫥨
𢖵傷
𢖵惜
句𠳨
𠾕𠳨
𠳨探
𦣰迷
𠫾𦣰
𦣰坭
思想
想𢖵
連想
感想
意想
回想
回想
空想
理想
沔北
沔南
沔中
屬地
屬𢚸
學屬𢚸
䏧屬
後屬地
法屬
屬性
註釋
注意
輔注
排書
排學
排欱
排報
排爫
排講
𨖅𢆥
𨑻𨖅
𨖅𠸜
𨖅張
伴鐄
𩵜鐄
鐄西
旬禮
上旬
眾碎
眾些
眾𠋥
𣛠𠖤
打𣛠
紙打𣛠
白金
合金
金英
金朋
𣋀金
當今
今古
歐洲
亞洲
非洲
洲南極
洲澳
洲大洋
滿洲
洲歐
洲亞
洲非
洲美
洲陸
籺珠
山林
火山
菭都
菭𣎃
菭歲
主日
生日
常日
日用
㗂日
𣷷日本
日本
𠁂𡮣
襖𨱽
朝𨱽
音樂
音樂古典
班頭
班𣈜
班迺
班𤎜
西班牙
王國西班牙
班最
首都
菭都
都市
故都
都條
都數
都𩈘
古都
姅𣎀
姑娘
娘仙
詩人
咹試
試舉
尋曉
曉別
棗西
大西洋
西原
西藏
西班牙
新西蘭
𪰂西
王國西班牙
鐄西
噠𠸜
噠航
噠價
評論
瓶水
𨷶行
𨷶數
茹𨷶
噲𨷶
起義
定義
義務
同義
無義
意義
解義
仁義
社會主義
最義
𠬃𠫾
𠬃戈
𠬃𧼋
𠬃𠅳
𠬃空
𠬃默
㐌𥹰
𥹰𠁀
𠃣𥹰
包𥹰
𣇞𥹰
徊𥹰
自𥹰
房客
房𥄬
房咹
房茶
藥房
國防
提防
防空
防備
防衛
位置
各位
香味
加味
𠹲牢
過𡗋
𡦂漢
𡦂曰
𡦂喃
𡦂十𧹼
𨔈𡦂
𡦂儒
行𡦂
𡦂眜
𠫾塊
𣷷日本
𣷷東
𣷷黰
𩵜𣷷
𦊚𣷷
春秋
節中秋
禮中秋
務秋
要求
求縁
求吀
呌求
求祝
𣇜𤎜
𤄯𤎜
𤎜𤊡
源𤎜
𤎜眜
班𤎜
𧼋遶
𠬃𧼋
𧼋步
盤蹎
𢟘蹎
蹎𩄲
𠫾蹎
蹎𢬣
章程
過程
程度
𪰂𠓀
𪰂北
𪰂西
𪰂南
𪰂東
茹𤤰
人員
人民
工人
主人
人類
人造
犯人
舉人
人生
人縁
婦人
詩人
人德
恩人
人類學
前人
要人
核仁
杏仁
不仁
仁義
保衛
保險
保助
保領
保全
𠰺保
名詞
區域
區庯
特區
獨立
藝術
美術
劍術
科學技術
技術
邊賴
𣛤坦
玉女
行客
房客
客地
爫客
茹客
上客
坦客
噲𪜀
呌噲
𠸜噲
噲𨷶
青龍
恐龍
下龍
囉喝
排欱
茹欱
𠬠𠄧
系統
統一
總統
𨷑頭
𨷑塘
𨷑𩈘
𨷑𠰘
朝廷
朝代
朝𨱽
朝高
朝鮮
朝阮
公佈
公認
公安
公式
公社
公爵
公司
𧵑公
𨀈頭
吶終
終結
𥆾終
於終
𧵑終
攎𢮪
𢮪攎
最少
少婦
年少
實現
現𫢩
出現
發現
現代
現在
現前
𨅸頭
𨅸𨖲
𣩂𨅸
𨅸䬔
扒頭
扒﨤
扒𤯩
扒焒
𨢇孟
孟劸
㛪𡮣
𠁂𡮣
𡥵𡮣
𡮣𡥵
𠊟𡮣
近視
指示
市場
都市
超市
城市
價市場
急時
高級
級下
共和
和平
𣇜𤎜
𣇜最
𢞂𥄬
𢞂𢚸
𢞂唭
𢞂情
𢗼𢞂
泰蘭
葻蘭
跢𣈖
𨔈跢𣈖
鬥跢
𥒥花
𥒥焒
渃𥒥
制度
𠫾𨔈
圖𨔈
𨔈跢𣈖
𨔈𡦂
吶𨔈
物體
動物
物料
生物
圖物
物理
物理學
事物
動物學
景物
物品
萬物
古生物學
博物
伴𫇰
如𫇰
連想
連結
聯關
聯邦
聯係
聯合
聯省
聯邦俄
聯營
𢘾𡗶
吒媄
𣩂吒
茹廚
偨廚
家庭
國家
家庭邊內
政治家
家庭治
作家
家景
儒家
參加
加增
加入
加味
加拿大
電話
電子
引電
畑電
絏電
書電子
香味
香料
鄉老
鄉俗
𡑝𠖤
場𠖤
𣛠𠖤
𢗼𢞂
軍隊
步隊
隊形
飛隊
隊軍
隊長
在𡊲
𡨹𡊲
固𨤔
𫥨𨤔
文𨤔
決定
一定
預定
定義
指定
決定論
定料
定例
前定
𢞂唭
加增
生員
學生
生𤯨
生日
生物
生學
回生
人生
古生物學
研究生
局生
生長
儒生
生下
生堆
太平
太子
太平洋
太原
制度
程度
印度
印度洋
印度教
角度
𡖡長
𫀅常
軍隊
軍事
海軍
隊軍
軍馬
𨖲𤖹
分𤖹
𠬠𠦳
公安
平安
仉𧁷
仉𡮈
仉𡘯
病院
治病
太平洋
東洋
洲大洋
大西洋
印度洋
北冰洋
南大洋
洋琴
南洋
回教
回音
回生
回想
回想
回春
回聲
回文
回吏
徊𠓀
徊芇
徊妬
徊𠸗
𠬠徊
徊𥹰
藝術
藝士
工藝
藝業
藝輔
𠊟𡮈
𠊟𡮣
堆欺
𠬠堆
堆𠀧
堆邊
堆𨑮
生堆
𠭤𠳒
𠭤恩
保全
柴棍
最多
最少
𣇜最
最高
黰最
最義
最後
最後書
最𣈜
班最
滝渃
𡶀滝
𡽫滝
紅河
紅十字
印度
印度洋
印度教
印劍
紙印
打價
打式
打憢
打𤊡
打𩃳
打𣈖盤
打𣛠
打動
紙打𣛠
𠃣一
𠃣𡗉
𠬠𠃣
𠃣欺
數𠃣
𠃣𫥨
𠃣歲
𠃣𠳒
𠃣固
𠃣𥹰
飛場
飛機
飛隊
飛劍
𠸗箕
𣋚箕
𢆥箕
𣈜箕
𣋚箕
博士
博學
茹博學
博物
伯𡛔
艚戰
小邦
聯邦
合邦
聯邦俄
藝士
博士
進士
俠士
牙士
藥士
瑞士
儒士
景物
景情
家景
入景
警察
警衛
預案
預見
預定
預報
預支
文化
化學
造化
化値
𢬣𤽸
政黨
黨治
黨史
黨長
𧁷巾
𧁷𠹾
𠹾𧁷
𧁷𢚸
𧁷𢣂
仉𧁷
革命
命𠊛
運命
世界
界限
界性
新世界
夾界
下界
阿彌陀佛
阿片
偨教
偨廚
偨𧆄
粓糝
𤗲巾
卒䏾
息䏾
𢣂䏾
打𩃳
𣈖畑
跢𣈖
𣈖𩵜
打𣈖盤
𣈖盤
𨔈跢𣈖
𣈖𦝄
𣈖䬔
𤎜𤊡
渃𤊡
打𤊡
払𤳇
偀払
偨𧆄
𧆄北
𧆄南
𧆄𥄬
襖𨱽
襖蘿
襖𠫾𩅹
𣈜𠸗
𠊛𠸗
𢆥𠸗
𠸗箕
𣋚𠸗
𡢐𠸗
徊𠸗
劍術
印劍
飛劍
家庭
家庭邊內
家庭治
停止
襖蘿
撐蘿𣘃
𧁷𠹾
𠹾𧁷
易𠹾
𧸝𠹾
聰明
通信
通報
通用
才能
財政
經財
貪財
題材
材料
電子
太子
探子
書電子
孔子
分子
撐䏧𡗶
䏧屬
紅河
河內
權力
固權
權能
法權
民權
特權
枝節
時節
節目
節中秋
節元旦
音節
多音節
發節
分𤾓
𠬠𤾓
翁𦓅
𦓅𠁀
𦓅哿
𦓅要
犯人
政治犯
犯法
𪝳些
接俗
接夾
𩈘陣
佈陣
戰陣
𫥨陣
失陣
爫衝
衝𨒺
病院
學院
下院
院研究
撐綠
撐蘿𣘃
撐䏧𡗶
茶撐
撐ㇴ
𣦍𥐉
𦊚方
𦊚𣷷
貪咹
貪財
𧖱貪
參加
參觀
參考
參戰
𣋀閻王
閻王星
𣋀海王
𣋀天王
王國西班牙
王國丹麥
王國英
精神
心神
女神
神學
易傷
易𠹾
易常
囉喝
𠳨探
探子
由探
探險
城庯
塘庯
區庯
庯舍
牟黰
黰最
粓黰
民黰
數黰
𣷷黰
正式
形式
打式
方式
公式
式咹
道佛
赤道
輔道
版圖
圖𨔈
圖物
圖㕵
前途
機關
機會
機體
飛機
投機
時機
基本
海外
海軍
海關
海口
上海
海南
航海
𣋀海王
海賊
地中海
黃海
黑海
四海
公佈
分佈
佈陣
𢂞媄
天下
天堂
青天
𣋀天王
𣋀天狼
天使
天鳥
主題
民主
主要
主人
主日
主治
社會主義
主體
主筆
𨑻𨖅
埋沒
𢟘蹎
意志
咹㕵
渃㕵
㕵𨢇
圖㕵
指數
指引
指定
指教
指南
指點
指示
指數經濟
雖然
首將
首都
首長
部首
助手
默𠶢
默感
默𠶢
𠬃默
𡦂十𧹼
泣坭
𠬠唏
歇唏
唏力
𦖑唏
皇帝
帝國德
社會
公社
社論
社會主義
預支
𡶀滝
𡶀焒
𡶀𡽫
𧿆𡶀
次𦒹
地方
方式
𦊚方
盤紙
錢紙
包紙
紙影
紙打𣛠
紙報
紙鉑
紙印
爫紙
紙曰書
次𬙞
𣈖𩵜
𩵜鐄
𩵜垌
𩵜𣷷
亞東
亞洲
洲亞
台𢷮
台為
㕵𨢇
𨢇孟
𨢇禮
息𨉟
息䏾
資訊
𡚢𡘯
𠬃𠅳
𠅳𨉟
指引
題引
證引
絏引
引電
引塘
引證
引解
冊引
律師
菲律賓
上旬
上海
上品
高上
上客
䬔東
䬔𩅹
䬔𦝄
𣈖䬔
䬔務
𨅸䬔
徐徐
徐䀡
預見
意見
動物
自動
動詞
動坦
能動
打動
動物學
被動
助動詞
眾𠋥
盤𢬣
盤蹎
打𣈖盤
𣈖盤
盤咹
盤論
盤紙
盤𫥨
盤碁
搬交
半島
𡉕島
襖𠫾𩅹
𡗶𩅹
籺𩅹
䬔𩅹
卒業
營業
藝業
工業
大工業
堆𨑮
𡏦𥩯
𢲧𥩯
𠰺學
𠰺保
𠅍𠰺
經濟
經營
經財
經史
指數經濟
首將
撐綠
牟綠
房𥄬
𢞂𥄬
𥄬迷
𥄬𤯆
𧆄𥄬
經濟
醫濟
指數經濟
國際
戰爭
戰鬥
艚戰
參戰
戰船
戰陣
夾戰
𢲧戰
扒焒
𥏌焒
影焒
𡶀焒
焒情
焒𢚸
𥒥焒
𡥵𤳇
払𤳇
𢢲𤳇
感𧡊
情感
感恩
感恩
感想
默感
感傷
感𢣂
佛教
阿彌陀佛
道佛
佛組
佛堂
政府
不幸
不常
不仁
不丹
作品
產品
製品
物品
上品
替品
藥品
品類
研究
考究
研究生
查究
中心研究
院研究
林學
山林
成功
𡏦𥩯
𠢞拖
拖頭
拖𠳒
包𣇞
包饒
包𠁟
別包
莊包𣇞
包書
包𢬣
空包𣇞
包紙
包𥹰
固體
空體
機體
物體
身體
簡體
主體
正體
政治
治病
政治家
政治犯
家庭治
內治
法治
自治
主治
黨治
地政治
價値
化値
多値
結果
結合
終結
總結
結縁
連結
𧖱貪
銀行𧖱
紅十字
𡦂十𧹼
十年
歐洲
洲歐
歐𪜀
娘仙
頭先
祖先
吝頭先
天下
下院
下筆
部下
下部
級下
下旗
下價
下界
下龍
下𨉟
下水
生下
下馬
㹥𣩂
㹥貓
店咹
嘲𢜠
祝𢜠
祝𢜠𢆥㵋
咹𢜠
𢜠歲
發展
發現
發問
發節
發音
成此
彈翁
彈婆
彈爭
翁老
𢢲老
鄉老
老婆
老教
船長
戰船
𢺺𢩿
𢺺𢬣
分𢺺
組織
佛組
組合
改組
祖國
祖先
咹粓
粓糝
粓黰
區域
地域
材料
物料
數料
香料
定料
藥料
場合
結合
集合
適合
合金
聯合
組合
合邦
合營
合分
組織
錢鉑
銅鉑
紙鉑
作者
讀者
看者
學者
記者
瓶水
𣋀水
湖水
下水
接俗
鄉俗
𠸜俗
世俗
俗語
爸媽
楛𣘃
交行
搬交
外交
𣈖畑
畑電
台𢷮
𢷮㵋
舉行
舉人
民舉
試舉
主筆
下筆
預案
保領
領事
總領事
作品
作者
工作
製作
作家
軍馬
下馬
馬力
牟色
特色
色𢢲
𥄬迷
𦣰迷
空氣
氣候
氣勢
壓力空氣
輕氣
教師
律師
師長
輪𠰘
𨷑𠰘
𤯆𠰘
𡨹𠰘
外𠰘
輔音
半輔音
藝輔
輔道
輔注
輔教
輔詞
婦女
少婦
產婦
婦人
暫時
暫別
歷史
史學
史冊
小史
黨史
經史
前史
使用
大使
天使
特使
鬥價
戰鬥
鬥爭
鬥跢
𣋀北斗
北斗七星
悔惜
𢖵惜
唯一
唯𠳐
反對
相反
結果
𥃑五果
籺椒
教育
教師
宗教
佛教
回教
教員
偨教
教皇
老教
指教
姑教
教務
印度教
孔教
教堂
禮教
儒教
輔教
精神
精明
行星
閻王星
北斗七星
火星
幸福
科學
科學技術
科長
長科
數量
力量
能量
茶撐
花茶
渃茶
房茶
𢢲縁
縁由
人縁
結縁
縁數
求縁
位置
吀纇
互助
保助
助動詞
助理
助手
小邦
小學
小史
小熊
場小學
落後
後裔
後屬地
後堂
最後
最後書
加入
入局
入學
入景
入口
入會
入內
才能
能量
能力
能動
內能
權能
萬能
葻花
葻蓮
葻蘭
節目
藥品
東藥
藥典
藥學
藥料
藥房
藥士
沒藥
𤯆眜
𤯆𠰘
𥄬𤯆
蹎𩄲
呌噲
呌求
呌𡗶
𩈘𦝄
𣈖𦝄
䬔𦝄
嘲𢜠
吀嘲
獨到
獨身
獨立
危險
章程
音樂
回音
音聲
同音
半音
音樂古典
觀音
元音
音節
多音節
發音
輔音
音響
半輔音
陰曆
陰謀
問題
主題
題材
題出
題引
論題
提及
提防
提高
前提
籺椒
籺珠
籺𩅹
籺蓮
夾籺
萬一
萬物
萬能
𠬠萬
製作
製造
製品
詞典
古典
音樂古典
字典
藥典
絏引
絏電
壓力
力量
權力
能力
唏力
壓力空氣
馬力
中國
內務
家庭邊內
婆內
內治
內能
入內
河內
內堂
內在
最多
多分
多値
多音節
㹥貓
盤碁
出口
入口
海口
口分
戶口
感恩
感恩
恩情
情恩
恩人
𠭤恩
界限
媒場
媒介
媒場學
憑證
證引
引證
影響
音響
地方
地點
地址
本地
屬地
地獄
中國
陸地
地勢
地域
客地
地中海
地球
地理
地政治
地質學
後屬地
時間
𣋀土
土耳其
競爭
地址
遺址
失常
失陣
陰曆
歷史
遊歷
莊他
幸福
不幸
杏仁
出版
出現
產出
題出
出口
提及
埃及
𥾘𥿗
併算
清算
夾戰
夾界
夾籺
夾𩈘
接夾
𡦂漢
漢越
漢文
英明
金英
㗂英
英國
王國英
言語
國語
俗語
語系
論語
次二
第二
二元
豫𨕭
盒書
嫩𥘷
𡽫滝
𡶀𡽫
𡽫渃
評論
爭論
決定論
盤論
論題
社論
論拠
論語
葻蓮
籺蓮
祝𢜠
祝𢜠𢆥㵋
求祝
祝書
發展
𡉕島
條件
近視
近代
𧁷巾
𤗲巾
庯舍
詞典
動詞
性詞
名詞
副詞
詞源
助動詞
輔詞
畢哿
必然
必要
第一
第二
經營
營業
大本營
大營
本營
營數
合營
聯營
國營
𣋀火
火山
火星
喂推
𤄯𤎜
𧿆𡶀
𠳐𠳒
唯𠳐
雖然
自然
必然
言語
關係
聯係
係數
系統
語系
保衛
警衛
民衛
防衛
碎伵
魚民
魚場
魚翁
執行
執政
斤書
孟劸
五常
𥃑五果
問題
學問
發問
悔恨
讎恨
銀行
銀行𧖱
調查
清查
考查
查究
𡦂喃
渃炊
遺產
產出
產品
共產
特產
產婦
孔子
孔教
決定
解決
決定論
壓力
壓力空氣
𡦂儒
大儒
茹儒
儒家
儒教
儒學
儒士
儒生
改革
改組
改良
參考
考究
考查
考古學
埃乃
𢺺𢩿
埋沒
沒藥
攎𢮪
𢮪攎
𢭲𢬣
𢭲細
㗂美
美術
洲美
北美
南美
世紀
紀元
𥾘𥿗
危險
保險
探險
𣊾𣇞
𣊾饒
包饒
𣊾饒
悔恨
悔惜
糖𥽢
研究
研究生
中心研究
院研究
互助
仕𫥨
天鳥
阿片
鴉片
欺迺
班迺
停止
撐ㇴ
𠫾ㇴ吏ㇴ
埃ㇴ
